{{- if .Values.computeDomainDevicePlugin.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fake-compute-domain-dra-plugin
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: fake-compute-domain-dra-plugin
subjects:
  - kind: ServiceAccount
    name: compute-domain-dra-plugin
    namespace: "{{ .Release.Namespace }}"
{{- end -}}