{{- if .Values.computeDomainDraPlugin.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: computedomain-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: computedomain-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: computedomain-controller
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: computedomain-controller
    spec:
      serviceAccountName: compute-domain-controller
      imagePullSecrets:
        - name: gcr-secret
      containers:
      - name: controller
        image: "{{ .Values.computeDomainController.image.repository }}:{{ .Values.computeDomainController.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.computeDomainController.image.pullPolicy }}"
        resources:
          {{- toYaml .Values.computeDomainController.resources | nindent 10 }}
{{- end }}

