{{- if and .Values.draPlugin.enabled .Values.draPlugin.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dra-example-driver.serviceAccountName" . }}
  namespace: {{ include "dra-example-driver.namespace" . }}
  labels:
    {{- include "dra-example-driver.labels" . | nindent 4 }}
  {{- with .Values.draPlugin.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end -}}
{{- end -}}
