{{- if .Values.computeDomainDevicePlugin.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "fake-gpu-operator.compute-domain-device-plugin.common.metadata.name" . }}
  labels:
    {{- include "fake-gpu-operator.compute-domain-device-plugin.common.metadata.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "fake-gpu-operator.compute-domain-device-plugin.common.podSelector" . | nindent 4 }}
  template:
    metadata:
      {{- include "fake-gpu-operator.compute-domain-device-plugin.common.podTemplate.metadata" . | nindent 6 }}
    spec:
      {{- include "fake-gpu-operator.compute-domain-device-plugin.common.podTemplate.spec" . | nindent 6 }}
      nodeSelector:
        nvidia.com/gpu.deploy.compute-domain-device-plugin: "true"
{{- end -}}