{{- if .Values.kwokComputeDomainDraPlugin.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kwok-compute-domain-dra-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kwok-compute-domain-dra-plugin
subjects:
  - kind: ServiceAccount
    name: kwok-compute-domain-dra-plugin
    namespace: "{{ .Release.Namespace }}"
{{- end }}
